Pilkarze/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('mainapp/', include('mainapp.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('editor/', include('django_summernote.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
# from django.contrib import admin

from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static



app_name = 'mainapp'

urlpatterns = [
    path('', views.base, name='base'),
    path('home/', views.home, name="home"),
    path('about/', views.about, name='about'),
    path('table/', views.table, name='table'),
    path('team/', views.EditTeam, name='team'),
    path('matches/', views.matches, name='matches'),
    path('register/', views.register_form, name='register'),
    path('new_team/', views.new_team, name='newTeam'),
    path('new_teamTrainer/', views.new_teamTrainer, name='newTeamTrainer'),
    path('create_player/', views.create_player, name='create_player'),
    path('edit_player/<int:pesel>/', views.edit_player, name='edit_player'),
    path('delete_player/<int:pesel>/', views.delete_player, name='delete_player'),
    path('show_team_stats/<int:idTeam>/', views.show_team_stats, name='show_team_stats'),
    path('protocol_refree/<int:idMatch>/', views.protocol_refree, name='protocol_refree'),
    path('edit_stats_player/<int:pesel>/<int:idMatch>/', views.edit_match, name='edit_stats_player'),
    path('create_match/', views.create_match, name='create_match'),
    path('delete_match/<int:idMatch>/', views.delete_match, name='delete_match')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/views.py
from django.conf.global_settings import MEDIA_URL
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.db import IntegrityError
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
from .models import *
from .Forms import UserForm, TeamForm, PlayerForm, PlayerEditForm, Protocol, MatchForm
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group


# Create your views here.


def base(request):
    return render(request, 'base.html')


def home(request):
    teams = Team.objects.all()
    return render(request, 'home.html', {'teams': teams})


def EditTeam(request):
    if request.user.groups.filter(name='Trener').exists():
        firstNameTrainer = request.user.first_name
        secondNameTrainer = request.user.last_name
        trainere = Trainer.objects.get_or_create(firstname=firstNameTrainer, secondname=secondNameTrainer)

        idTrainer = trainere[0].id_trainer

        try:
            idTeam = Team.objects.get(id_trainer=idTrainer).id_team
            number_of_players = Player.objects.filter(id_team=idTeam).count()

            logo = Team.objects.get(id_trainer=idTrainer).logo
            date_creation = Team.objects.get(id_trainer=idTrainer).date_creation

        except(KeyError, Team.DoesNotExist):
            return HttpResponseRedirect(reverse('mainapp:newTeamTrainer'))

        nameTeam = Team.objects.get(id_trainer=idTrainer).name
        players = Player.objects.filter(id_team=idTeam)
        return render(request, 'team.html',
                      {'players': players, 'nameTeam': nameTeam, 'logo': logo, 'date_creation': date_creation,
                       'number_of_players': number_of_players})
    else:
        return render(request, 'error.html', {'message': "Only trainers have permission to this section"})


def matches(request):
    queues = Queue.objects.all()
    try:
        selected_choice = Queue.objects.get(idQueue=request.GET['queueid'])
        matches = Match.objects.filter(idQueue=selected_choice)
    except(KeyError, Queue.DoesNotExist):
        return render(request, 'matches.html', {'queues': queues})
    else:
        return render(request, 'matches.html',
                      {'matches': matches, 'queues': queues, 'selected_choice': selected_choice})


def table(request):
    teamstats = StatsTeam.objects.all().order_by('-numberOfScores', '-numberOfMatchesWon')

    king_of_goals = StatsPlayerLeague.objects.all().order_by('-numberOfGoals')
    return render(request, 'teamstats.html', {'teamstats': teamstats, 'king_of_goals': king_of_goals})


def about(request):
    try:
        model = HTMLModels.objects.get(page_name='about')
    except ObjectDoesNotExist:
        return render(request, 'about.html')

    return render(request, 'about.html', {'model': model})


def register_form(request):
    form = UserForm(request.POST)

    if form.is_valid():
        user = form.save()
        group = form.cleaned_data['group_name']
        first_name = form.cleaned_data['first_name']
        second_name = form.cleaned_data['last_name']
        group.user_set.add(user)

        if str(group) == "Trener":
            trener = Trainer.objects.create(firstname=first_name, secondname=second_name)
            trener.save()
        return HttpResponseRedirect(reverse('mainapp:home'))
    else:
        form = UserForm()

    return render(request, 'register_form.html', {'form': form})


@login_required
def new_team(request):
    form = TeamForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('mainapp:home'))
    return render(request, 'team_form.html', {'form': form})


@login_required
def new_teamTrainer(request):
    form = TeamForm(request.POST or None, request.FILES or None)
    firstName = request.user.first_name
    lastName = request.user.last_name
    id_trainer = Trainer.objects.get(firstname=firstName, secondname=lastName).id_trainer
    if form.is_valid():
        form.save()
        name_team = form.cleaned_data['name']
        date_creation = form.cleaned_data['date_creation']
        # Team.objects.get(name=name_team,date_creation=date_creation)
        Team.objects.filter(name=name_team, date_creation=date_creation).update(id_trainer=id_trainer)
        return HttpResponseRedirect(reverse('mainapp:home'))
    return render(request, 'team_form.html', {'form': form})


@login_required
def create_player(request):
    if request.user.groups.filter(name='Trener').exists():

        form = PlayerForm(request.POST)
        firstName = request.user.first_name
        lastName = request.user.last_name
        id_trainer = Trainer.objects.get(firstname=firstName, secondname=lastName).id_trainer
        id_team = Team.objects.get(id_trainer=id_trainer).id_team

        # if Player.objects.filter(id_team=id_team).count() > 3:
        #     return render(request, 'error.html', {'message': "You can only create 2 players"})

        if form.is_valid():
            form.save()
            psl = form.cleaned_data['pesel']
            Player.objects.filter(pesel=psl).update(id_team=id_team)
            return HttpResponseRedirect(reverse('mainapp:team'))

        return render(request, 'RegisterTeamPlayer.html', {'form': form})
    else:
        return render(request, 'error.html', {'message': "Only trainers have permission to this section"})


@login_required
def edit_player(request, pesel):
    player = get_object_or_404(Player, pk=pesel)

    form = PlayerEditForm(request.POST or None, request.FILES or None, instance=player)

    if form.is_valid():
        status = form.cleaned_data['statusHealth']
        position = form.cleaned_data['position']
        age = form.cleaned_data['age']

        Player.objects.filter(pesel=pesel).update(statusHealth=status)
        Player.objects.filter(pesel=pesel).update(age=age)
        Player.objects.filter(pesel=pesel).update(position=position)
        return HttpResponseRedirect(reverse('mainapp:team'))

    return render(request, 'EditPlayer.html', {'form': form})


@login_required
def delete_player(request, pesel):
    player = get_object_or_404(Player, pk=pesel)

    if request.method == "POST":
        player.delete()
        return HttpResponseRedirect(reverse('mainapp:team'))

    return render(request, 'accept_delete_player.html', {'player': player})


def show_team_stats(request, idTeam):
    stats_team = get_object_or_404(StatsTeam, pk=idTeam)
    team = get_object_or_404(Team, pk=idTeam)
    count_scored_goals = 0
    for player in Player.objects.filter(id_team=idTeam):
        x = StatsPlayerLeague.objects.get(pesel=player.pesel).numberOfGoals
        count_scored_goals = count_scored_goals + x

    try:
        id_trainer = Trainer.objects.get(team__id_team=idTeam).id_trainer
        trainer = Trainer.objects.get(id_trainer=id_trainer)

    except ObjectDoesNotExist:
        return render(request, 'error.html', {'message': "Error"})
    return render(request, 'StatsTeam.html', {'stats_team': stats_team, 'team': team, 'trainer': trainer, 'count_scored_goals': count_scored_goals})


@login_required
def protocol_refree(request, idMatch):
    if request.user.groups.filter(name='Sedzia').exists():
        try:
            match = get_object_or_404(Match, pk=idMatch)
            home = match.Home
            guest = match.Guest
            id_home_team = Team.objects.get(id_team=home.id_team)
            id_guest_team = Team.objects.get(id_team=guest.id_team)

            for player in Player.objects.filter(id_team=id_home_team):
                try:
                    StatsPlayerMatch.objects.get(player=player, idMatch=match)
                except ObjectDoesNotExist:
                    StatsPlayerMatch.objects.create(player=player, idMatch=match)

            for player in Player.objects.filter(id_team=id_guest_team):
                try:
                    StatsPlayerMatch.objects.get(player=player, idMatch=match)
                except ObjectDoesNotExist:
                    StatsPlayerMatch.objects.create(player=player, idMatch=match)

            players_home = Player.objects.filter(id_team=id_home_team)
            players_guest = Player.objects.filter(id_team=id_guest_team)

        except ObjectDoesNotExist:
            return render(request, 'error.html', {'message': "That match doesnt exist"})

        return render(request, 'protocol_refree.html', {'match': match, 'players_home': players_home,
                                                        'players_guest': players_guest, 'homeTeam': id_home_team,
                                                        'guestTeam': id_guest_team})

    return render(request, 'error.html', {'message': "Only referees have permission to this section"})


@login_required
def edit_match(request, pesel, idMatch):
    global form, homeGoals, guestGoals

    if request.user.groups.filter(name='Sedzia').exists():

        id_player = get_object_or_404(Player, pk=pesel)
        stats = get_object_or_404(StatsPlayerMatch, player=id_player, idMatch=idMatch)
        home_team = Match.objects.get(idMatch=idMatch).Home
        guest_team = Match.objects.get(idMatch=idMatch).Guest
        match = get_object_or_404(Match, pk=idMatch)
        count_home_goals = 0
        count_guest_goals = 0
        current_goals = 0

        form = Protocol(request.POST or None, instance=stats)

        if form.is_valid():
            goals = form.cleaned_data['numberOfGoals']
            yellow_card = form.cleaned_data['numberOfYellowCard']
            StatsPlayerMatch.objects.filter(idMatch=idMatch, player=id_player).update(numberOfGoals=goals)

mainapp/templates/Edit_stats_player.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block headerbottomright %}

<a>Edycja statystyk zawodnika</a>
{% endblock %}

{% block content-right %}

    <div class="card" style="width: 25rem;">
      <div class="card-body">
        <h3 class="card-title">Edycja statystyk zawodnika</h3>
          <form method = "post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|bootstrap }}
              <br>

            <button type = "submit" class="btn btn-primary" >Zatwierdz <i class="fas fa-sign-in-alt"></i></button>
          </form>


      </div>
    </div>

<br>



       <form method="post" action="{% url 'mainapp:protocol_refree' idmatch %}">
           {% csrf_token %}
           <button type='submit ' class="btn btn-light" >Cofnij <i class="fas fa-backward"></i></button>
        </form>

{% endblock %}

mainapp/templates/RegisterTeamPlayer.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block headerbottomright %}
<a>Dodaj pilkarza</a>
{% endblock %}

{% block content-right %}

    <div class="card" style="width: 25rem;">
      <div class="card-body">
        <h5 class="card-title">Dodaj Pilkarza</h5>
          <form method = "post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|bootstrap }}
              <br>

              <button type = "submit" class="btn btn-primary" >Dodaj <i class="fas fa-plus"></i></button>

          </form>

      </div>

    </div>

            <form method="post" action="{% url 'mainapp:team' %}">
            {% csrf_token %}
           <button type='submit' class="btn btn-light" >Cofnij <i class="fas fa-backward"></i></button>
            </form>

<br>

{% endblock %}

mainapp/templates/accept_delete_match.html
{% extends 'base.html' %}

{% block headerbottomright %}
    <a>ALERT</a>
{% endblock %}

{% block content-right %}

    <p>Czy napewno chcesz usunac mecz {{match.Home}} {{match.Guest}} z dnia {{ match.startDate }} ?</p>
    <br>
    <hr>
            <form method="post">
            {% csrf_token %}
            <button type='submit' class="btn btn-primary" >Zatwierdz <i class="fas fa-check"></i> </button>
            </form>

    <br>
            <form method="post" action="{% url 'mainapp:matches' %}">
            {% csrf_token %}
            <button type='submit' class="btn btn-light" >Cofnij <i class="fas fa-backward"></i></button>
            </form>


{% endblock %}

mainapp/templates/base.html
{% load static %}
{% load user_tags %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %} LIGA UNIWERSYTECKA {% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:500" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Antonio:wght@500&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/f2918ceb1f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" integrity="sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
    <header>
        <div class="header-wrapper">
            <div class="header-wrapper-left">
                <a href="{% url 'mainapp:home' %}">HOME</a>
                <a href="{% url 'mainapp:about' %}">ABOUT</a>
                <a href="{% url 'mainapp:table' %}">TABLE</a>
                <a href="{% url 'mainapp:matches' %}">MATCHES</a>

                {% if user|has_group:"Trener" %}
                <a href="{% url 'mainapp:team' %}">TEAM</a>
                {% endif %}


            </div>
            <div class="header-wrapper-right">
                {% if user.is_authenticated %}
                <h7> Witaj {{user.username}}</h7>
                <a href="{% url 'logout'%}">Wyloguj</a>
                {% else %}
                    <a href ="{% url 'mainapp:register' %}">Zarejestruj sie<i class="fas fa-user-plus" style="margin-left:5px"></i></a>
                    <a href ="{% url 'login'%}">Zaloguj <i class="fas fa-sign-in-alt" style="margin-left:5px"></i></a>
                {% endif %}
            </div>
        </div>
        <div class="header-wrapper-bottom">
            <div class="header-wrapper-bottom-left">

            </div>
            <div class="header-wrapper-bottom-right">
                <a href="{% url 'mainapp:home' %}" style="color: rgb(29, 34, 40);text-decoration: none"></i>HOME</a>
                <a></a>
                {% block headerbottomright %}
                <a>ABOUT</a>
                {% endblock %}
            </div>
        </div>
    </header>
    <div class="content">
        <div class="content-wrapper">
            <div class="content-left">
            </div>
            <div class="content-right">
            {% block content-right %}
            <a>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer tincidunt nunc varius
                dolor efficitur, elementum varius sem interdum. Nunc est sapien, commodo sit amet laoreet nec,
                condimentum id ante. Sed vehicula auctor ipsum id sollicitudin. Donec ac ligula sollicitudin,
                fringilla libero eu, sodales est. Suspendisse quis sapien id orci tincidunt tempor. Donec et
                mauris porta, auctor quam ac, eleifend elit. Donec eu mi ac lectus auctor viverra.
                Donec consequat dui in turpis maximus, a hendrerit neque pulvinar. Nullam dictum sollicitudin
                tortor ut tincidunt. Etiam gravida urna id arcu suscipit, eu finibus ante mattis.
                Etiam blandit quam nisi, ac bibendum leo porta eget. Duis nec ex ut nibh tristique varius.
                Duis egestas nisi eget justo pulvinar viverra. <br>

                Proin ex lorem, varius eu dapibus nec, fringilla non ligula. Proin et pharetra magna.
                Nullam in pharetra metus. Sed elementum, orci vitae cursus accumsan, dui nisi tristique orci,
                vitae mollis justo quam et libero. Pellentesque habitant morbi tristique senectus et netus et
                malesuada fames ac turpis egestas. Sed consequat pellentesque velit, nec facilisis lorem ornare
                ut. Nullam sollicitudin dui elementum magna aliquam vestibulum. Cras dapibus nisl ac tincidunt
                tempus. Morbi aliquet, mi semper interdum lobortis, leo sem auctor odio, sed fermentum tellus felis
                vel justo. Nullam luctus nulla in sapien consectetur laoreet. Nulla quis laoreet turpis.
                Etiam mattis mi velit, eget rhoncus quam ornare lobortis. Fusce commodo vehicula sodales.<br>

                Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;
                Integer sed pretium ipsum, eget sollicitudin ex. Quisque lectus odio, sodales vitae tellus
                nec, dignissim porta urna. Nunc imperdiet varius maximus. Mauris in faucibus ipsum.
                Proin finibus viverra diam, vitae maximus sapien faucibus et. Donec fringilla, dui ut
                porta imperdiet, eros elit elementum arcu, ut ullamcorper arcu odio ut leo. Duis ut aliquet
                ante. Nulla ullamcorper ac risus non molestie.</a>
             {% endblock %}
            </div>
        </div>
    </div>

</body>
</html>

mainapp/templates/createMatch.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block headerbottomright %}
<a>Dodaj match</a>
{% endblock %}

{% block content-right %}

    <div class="card" style="width: 25rem;">
      <div class="card-body">
        <h5 class="card-title">Dodaj Pilkarza</h5>
          <form method = "post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|bootstrap }}
              <br>
              <button type = "submit" class="btn btn-primary" >Dodaj <i class="fas fa-plus"></i></button>

          </form>

      </div>

    </div>

            <form method="post" action="{% url 'mainapp:matches' %}">
            {% csrf_token %}
           <button type='submit' class="btn btn-light" >Cofnij <i class="fas fa-backward"></i></button>
            </form>

<br>

{% endblock %}

mainapp/templates/error.html
{% extends 'base.html' %}

{% block headerbottomright %}
    <a>ERROR</a>
{% endblock %}

{% block content-right %}
    {{ message }}
{% endblock %}

mainapp/templates/home.html
{% extends 'base.html' %}

{% block headerbottomright %}
<a>LIGA</a>
{% endblock %}

{% block content-right %}

{#{%for team in teams%}#}
{#<div class="card" style="width: 18rem;">#}
{#  <img src="{{ MEDIA_URL }}{{team.logo}}" class="logo-druzyna">#}
{#  <div class="card-body">#}
{#    <h5 class="card-title">{{team}}</h5>#}
{#    <p class="card-text">{{team.date_creation}}</p>#}
{#  </div>#}
{#</div>#}
        <div class="card-group-wrapper-column">
{%for team in teams%}
        <div class="card-group">
          <div class="card" style="width: 20rem;">
            <img src="{{ MEDIA_URL }}{{team.logo}}" class="card-img-top" alt="...">
            <div class="card-body">
                <p class="card-title"> <strong>{{ team.name }} </strong></p>
              <p class="card-text">Data założenia: {{ team.date_creation }}</p>
            </div>
            <div class="card-footer">
                <a href = "{% url 'mainapp:show_team_stats' team.id_team %}"><small class="text-muted"><button type="button" class="btn btn-secondary btn-sm">Wyświetl statystyki w lidze</button></small></a>
            </div>
          </div>
        </div>





<br>

{%endfor%}
        </div>

{% endblock %}

mainapp/templates/matches.html
{% extends 'base.html' %}
{% load user_tags %}

{% block headerbottomright %}
    <a>TERMINARZ MECZY</a>
{% endblock %}

{% block content-right %}
    <div class="content-matches">

        <div class="submitButtons">

                <form action="{% url 'mainapp:matches' %}" method="get">
                <label> <strong> Wybierz kolejke: </strong> </label>
                <select name="queueid" style="margin-left: 10px">
                    {% for queue in queues %}

                        <option {% if queue == selected_choice %} selected{% endif %} name="choice"
                                                                                      value="{{ queue.idQueue }}">{{ queue }}</option>
                    {% endfor %}
                </select>
                <button type="submit" id="getButton" class="btn btn-primary" style="margin-left: 10px"><i
                        class="fa fa-cog"></i> Wybierz
                </button>
                </form>

        </div>

        <table id="gameDataTable">
            <tr class="col">
                <th class="title">Home Team</th>
                <th class="title">Guest Team</th>
                <th class="title">Date</th>
                <th class="title">Score</th>
                {% if request.user|has_group:"Sedzia"%}
                <th class="title">Edit</th>
                {%  endif %}

            </tr>
            {% for match in matches %}

                <tr class="wpos">
                    <td>{{ match.Home }}</td>
                    <td>{{ match.Guest }}</td>
                    <td>{{ match.startDate }}</td>
                    {% if match.finished_by_refree != -1 %}
                    <td>{{ match.homeGoals }}:{{ match.guestGoals }}</td>
                    {% else %}
                    <td>{{ "- " }}:{{ " -" }}</td>
                    {%  endif %}
                    {% if request.user|has_group:"Sedzia"%}
                    <td><a href = "{% url 'mainapp:protocol_refree' match.idMatch %}"><button type="button" class="btn btn-primary"><i class="fas fa-user-edit"></i></button></a></td>
                    {%  endif %}
                </tr>
            {% endfor %}


        </table>

    </div>
{% endblock %}

mainapp/templates/protocol_refree.html
{% extends 'base.html' %}

{% block headerbottomright %}
    <a>MATCH</a>
{% endblock %}

{% block content-right %}
    <div class="content-match-edit">

        <div class="content-match-edit-wrapper">
            <div class="content-match-homeguest-wrapper">
                <img src="{{ MEDIA_URL }}{{homeTeam.logo}}" class="logo-druzyna" width="200" height="250">
                <h2><strong>{{ match.Home }}</strong></h2>
            </div>
            <div class="content-match-homeguest-wrapper">
                <img src="{{ MEDIA_URL }}{{guestTeam.logo}}" class="logo-druzyna" width="200" height="250">
                <h2><strong>{{ match.Guest }}</strong></h2>
            </div>
        </div>

        <h2><strong> Score </strong></h2>

        <div class="ui statistics">
          <div class="statistic">
            <div class="value">
              {% if match.finished_by_refree != -1 %}
                    <td>{{ match.homeGoals }}</td>
                    {% else %}
                    <td>{{ "- " }}</td>
                    {%  endif %}
            </div>
            <div class="label">
            </div>

          </div>
          <div class="statistic">
            <div class="value">
                {% if match.finished_by_refree != -1 %}
                    <td>{{ match.guestGoals }}</td>
                    {% else %}
                    <td>{{ "- " }}</td>
                    {%  endif %}
            </div>
          </div>
        </div>

        <div class="match-edit-players-wrapper">
                <div class="match-edit-players-home">
        {% for player in players_home %}
                <p>
                {{ forloop.counter }}
                {{ player.firstName }}
                {{ player.secondName }}
                {{ player.age }}
                {{ player.position }}
                <td><a href = "{% url 'mainapp:edit_stats_player' player.pesel match.idMatch%}">
                    <button type="button" class="btn btn-primary"><i class="fas fa-pen-square"></i></button></a></td>

                </p>
        {% empty %}
            <p>Aktualnie nie ma zadnych pilkarzy </p>
        {% endfor %}
                </div>
                <div class="match-edit-players-guest">
            {% for player in players_guest %}

                <p>
                {{ forloop.counter }}
                {{ player.firstName }}
                {{ player.secondName }}
                {{ player.age }}
                {{ player.position }}
                <td><a href = "{% url 'mainapp:edit_stats_player' player.pesel match.idMatch%}"><button type="button" class="btn btn-primary"><i class="fas fa-pen-square"></i></button></a></td>
                </p>
        {% empty %}
            <p>Aktualnie nie ma zadnych pilkarzy </p>
            {% endfor %}
                </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/team.html
{% extends 'base.html' %}

{% block headerbottomright %}
    <a>TEAM</a>
{% endblock %}

{% block content-right %}
    <div class="content-players">
<!--        <p> {{logo}}</p>-->

          <img src="{{ MEDIA_URL }}{{logo}}" class="logo-druzyna" width="200" height="250"> <!--ADAM TUTAJ MUSISZ naprawic mi wyswietlanie logo - te twoje rwd / flexbox cos tam -->
        <h2>{{ nameTeam }}</h2>
        <h3>Data zalozenia: {{ date_creation }}</h3>
        <br>
        {% if number_of_players < 25 %}
            <a href = "{% url 'mainapp:create_player' %}"><button type="button" class="btn btn-primary">Dodaj piłkarza <i class="fas fa-plus"></i></button></a>
        {% endif %}
        <hr>
    <table>
        <tr class="col">
            <th>#</th>
            <th>First Name</th>
            <th>Second Name</th>
            <th>Age</th>
            <th>Position</th>
            <th>Status Health</th>
            <th>Team</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        {% for player in players %}

            <tr class="wpos">
                <td>{{ forloop.counter }}</td>
                <td>{{ player.firstName }}</td>
                <td>{{ player.secondName }}</td>
                <td>{{ player.age }}</td>
                <td>{{ player.position }}</td>
                <td>{{ player.statusHealth }}</td>
                <td>{{ player.id_team.name }}</td>
                <td><a href = "{% url 'mainapp:edit_player' player.pesel %}"><button type="button" class="btn btn-primary"><i class="fas fa-user-edit"></i></button></a></td>
                <td><a href = "{% url 'mainapp:delete_player' player.pesel %}"><button type="button" class="btn btn-danger"><i class="fas fa-user-minus"></i></button></a></td>
            </tr>
        {% empty %}
            <p>Aktualnie nie ma zadnych pilkarzy </p>

        {% endfor %}

    </table>
    </div>
{% endblock %}